WebPratice/WebApplication1/Models/ErrorViewModel.cs
using System;

namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebPratice/WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebPratice/WebApplication1/Controllers/WaterConsumptionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ConsoleApp1.Model;
using ConsoleApp1.Service;
using WebApplication1.Data;

namespace WebApplication1.Controllers
{
    [Route("[controller]")]
    public class WaterConsumptionsController : Controller
    {
        private ApplicationDbContext _context;

        public WaterConsumptionsController(ApplicationDbContext context)
        {
            this._context = context;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return SearchUnit("");
        }

        [HttpGet("Import")]
        public IActionResult Import()
        {
            string filePath = ConsoleApp1.Utlis.FilePath.getFilePath("7D1311DD-E1DE-4B01-A5ED-1FC589A7C082.json");

            List<WaterConsumption> results = new ImportJsonService().read(filePath);

            _context.waterConsumptions.AddRange(results);
            _context.SaveChanges();

            return Content("OK");
        }

        [HttpGet("DeleteAll")]
        public IActionResult DeleteAll()
        {
            foreach(var data in _context.waterConsumptions)
            {
                _context.waterConsumptions.Remove(data);
            }
            _context.SaveChanges();

            return Content("OK");
        }

        [HttpPost("SearchUnit")]
        public IActionResult SearchUnit(string unitName)
        {
            var query = _context.waterConsumptions.AsQueryable();
            
            if (!String.IsNullOrEmpty(unitName))
            {
                query = query.Where(e => e.executingUnit == unitName);
            }
            query = query.OrderByDescending(x => x.Id);
            //var results = query.Take(10);

            return View("Index", query.ToList());
        }

        [HttpGet("Create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("Create")]
        public IActionResult Create(WaterConsumption create)
        {
            _context.waterConsumptions.Add(create);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet("Edit/{id}")]
        public IActionResult Edit(int id)
        {
            var edit = _context.waterConsumptions.Find(id);

            return View(edit);
        }

        [HttpPost("Edit/{id}")]
        public IActionResult Edit(WaterConsumption edit)
        {
            _context.Entry(edit).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            _context.waterConsumptions.Update(edit);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet("Delete/{id}")]
        public IActionResult Delete(int id)
        {
            var water = _context.waterConsumptions.Find(id);

            _context.waterConsumptions.Remove(water);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

WebPratice/WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebPratice/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WaterConsumptions" asp-action="Index">WaterConsumption</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebPratice/WebApplication1/Views/WaterConsumptions/Create.cshtml
@model ConsoleApp1.Model.WaterConsumption

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>WaterConsumption</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="consumptionOfWater" class="control-label"></label>
                <input asp-for="consumptionOfWater" class="form-control" />
                <span asp-validation-for="consumptionOfWater" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="executingUnit" class="control-label"></label>
                <input asp-for="executingUnit" class="form-control" />
                <span asp-validation-for="executingUnit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="populationServed" class="control-label"></label>
                <input asp-for="populationServed" class="form-control" />
                <span asp-validation-for="populationServed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="remarks" class="control-label"></label>
                <input asp-for="remarks" class="form-control" />
                <span asp-validation-for="remarks" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="theDailyDomesticConsumptionOfWaterPerPerson" class="control-label"></label>
                <input asp-for="theDailyDomesticConsumptionOfWaterPerPerson" class="form-control" />
                <span asp-validation-for="theDailyDomesticConsumptionOfWaterPerPerson" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="year" class="control-label"></label>
                <input asp-for="year" class="form-control" />
                <span asp-validation-for="year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebPratice/WebApplication1/Views/WaterConsumptions/Edit.cshtml
@model ConsoleApp1.Model.WaterConsumption

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>WaterConsumption</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="consumptionOfWater" class="control-label"></label>
                <input asp-for="consumptionOfWater" class="form-control" />
                <span asp-validation-for="consumptionOfWater" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="executingUnit" class="control-label"></label>
                <input asp-for="executingUnit" class="form-control" />
                <span asp-validation-for="executingUnit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="populationServed" class="control-label"></label>
                <input asp-for="populationServed" class="form-control" />
                <span asp-validation-for="populationServed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="remarks" class="control-label"></label>
                <input asp-for="remarks" class="form-control" />
                <span asp-validation-for="remarks" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="theDailyDomesticConsumptionOfWaterPerPerson" class="control-label"></label>
                <input asp-for="theDailyDomesticConsumptionOfWaterPerPerson" class="form-control" />
                <span asp-validation-for="theDailyDomesticConsumptionOfWaterPerPerson" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="year" class="control-label"></label>
                <input asp-for="year" class="form-control" />
                <span asp-validation-for="year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebPratice/WebApplication1/Views/WaterConsumptions/Index.cshtml
@{
    ViewData["Title"] = "WaterConsumption";
}
@model IEnumerable<ConsoleApp1.Model.WaterConsumption>

<style>

    table, th, td {
        border-bottom: 1px solid #ddd;
        border-collapse: collapse;
        padding: 15px;
        text-align: left;
    }
</style>

<h1>WaterConsumption List</h1>

<a href="/WaterConsumptions/Create">新增</a>

<form action="/WaterConsumptions/SearchUnit" method="post">

    <label>請輸入縣市別:</label><br>

    <input type="text" id="unitName" name="unitName" placeholder="UnitName">
    <input type="submit" value="查詢" />
</form>

<table>
    <thead>
        <tr>
            <th>生活用水量</th>
            <th>縣市別</th>
            <th>供水人數</th>
            <th>每人每日生活用水量(公升)</th>
            <th>統計年度</th>
            <th>備註</th>
            <th></th>
        </tr>
    </thead>
    <tbody>

    @if (Model != null)
    {
        @foreach (ConsoleApp1.Model.WaterConsumption w in Model)
        {
            <tr>
                <td>@w.consumptionOfWater</td>
                <td>@w.executingUnit</td>
                <td>@w.populationServed</td>
                <td>@w.theDailyDomesticConsumptionOfWaterPerPerson</td>
                <td>@w.year</td>
                <td>@w.remarks</td>
                <td>
                    <a href="/WaterConsumptions/Edit/@w.Id">Edit</a> |
                    <a id="delBtn" href="/WaterConsumptions/Delete/@w.Id">Delete</a>
                </td>
            </tr>
        }
    }
    </tbody>
</table>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {

            $("#delBtn").click(function () {

                return confirm("Are you sure?");
            });
        })
    </script>
}